INSERT INTO students (id, name, email, age) VALUES
(1, 'Nguyễn Văn A', 'a@student.edu', 20),
(2, 'Trần Thị B', 'b@student.edu', 21),
(3, 'Lê Văn C', 'c@student.edu', 19),
(4, 'Phạm Văn D', 'd@student.edu', 22),
(5, 'Hoàng Thị E', 'e@student.edu', 20),
(6, 'Vũ Văn F', 'f@student.edu', 23),
(7, 'Đặng Thị G', 'g@student.edu', 21),
(8, 'Bùi Văn H', 'h@student.edu', 19),
(9, 'Đỗ Thị I', 'i@student.edu', 22),
(10, 'Ngô Văn K', 'k@student.edu', 20),
(11, 'Lý Thị L', 'l@student.edu', 21),
(12, 'Phan Văn M', 'm@student.edu', 23),
(13, 'Trịnh Thị N', 'n@student.edu', 19),
(13, 'Văn Thị A', 'abc@student.edu', 19);